// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approvals.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateApprovalStep = `-- name: ActivateApprovalStep :execrows
UPDATE approvals
SET activated_at = now()
WHERE transaction_id = $1 AND step = $2 AND activated_at IS NULL AND cancelled_at IS NULL
`

type ActivateApprovalStepParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	Step          int16     `json:"step"`
}

func (q *Queries) ActivateApprovalStep(ctx context.Context, arg ActivateApprovalStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateApprovalStep, arg.TransactionID, arg.Step)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const approvalHasDecision = `-- name: ApprovalHasDecision :one
SELECT EXISTS (SELECT 1 FROM approval_decisions WHERE approval_id = $1) AS has_decision
`

func (q *Queries) ApprovalHasDecision(ctx context.Context, approvalID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, approvalHasDecision, approvalID)
	var has_decision bool
	err := row.Scan(&has_decision)
	return has_decision, err
}

const cancelPendingApprovals = `-- name: CancelPendingApprovals :execrows
UPDATE approvals
SET cancelled_at = now()
WHERE transaction_id = $1 AND cancelled_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM approval_decisions d WHERE d.approval_id = approvals.id)
`

func (q *Queries) CancelPendingApprovals(ctx context.Context, transactionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingApprovals, transactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createApproval = `-- name: CreateApproval :exec
INSERT INTO approvals (transaction_id, approver_id, approver_name, approver_email, approver_role, step, activated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateApprovalParams struct {
	TransactionID uuid.UUID          `json:"transaction_id"`
	ApproverID    uuid.UUID          `json:"approver_id"`
	ApproverName  string             `json:"approver_name"`
	ApproverEmail string             `json:"approver_email"`
	ApproverRole  string             `json:"approver_role"`
	Step          int16              `json:"step"`
	ActivatedAt   pgtype.Timestamptz `json:"activated_at"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) error {
	_, err := q.db.Exec(ctx, createApproval,
		arg.TransactionID,
		arg.ApproverID,
		arg.ApproverName,
		arg.ApproverEmail,
		arg.ApproverRole,
		arg.Step,
		arg.ActivatedAt,
	)
	return err
}

const createApprovalDecision = `-- name: CreateApprovalDecision :one
INSERT INTO approval_decisions (approval_id, decided_by, decided_by_name, decided_by_email, decided_by_role, decision, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING
    id, approval_id, decided_by, decided_by_name, decided_by_email, decided_by_role, decision, notes, decided_at
`

type CreateApprovalDecisionParams struct {
	ApprovalID     uuid.UUID   `json:"approval_id"`
	DecidedBy      uuid.UUID   `json:"decided_by"`
	DecidedByName  string      `json:"decided_by_name"`
	DecidedByEmail string      `json:"decided_by_email"`
	DecidedByRole  string      `json:"decided_by_role"`
	Decision       string      `json:"decision"`
	Notes          pgtype.Text `json:"notes"`
}

func (q *Queries) CreateApprovalDecision(ctx context.Context, arg CreateApprovalDecisionParams) (ApprovalDecision, error) {
	row := q.db.QueryRow(ctx, createApprovalDecision,
		arg.ApprovalID,
		arg.DecidedBy,
		arg.DecidedByName,
		arg.DecidedByEmail,
		arg.DecidedByRole,
		arg.Decision,
		arg.Notes,
	)
	var i ApprovalDecision
	err := row.Scan(
		&i.ID,
		&i.ApprovalID,
		&i.DecidedBy,
		&i.DecidedByName,
		&i.DecidedByEmail,
		&i.DecidedByRole,
		&i.Decision,
		&i.Notes,
		&i.DecidedAt,
	)
	return i, err
}

const getApprovalForDecide = `-- name: GetApprovalForDecide :one
SELECT a.id, a.transaction_id, a.approver_id, a.approver_name, a.approver_email,
       a.approver_role, a.step, a.activated_at, a.cancelled_at, a.created_at,
       t.organization_id, t.status AS transaction_status,
       t.description, t.total_amount, t.currency, t.created_by,
       t.created_by_name, t.created_by_email
FROM approvals a
         JOIN transactions t ON t.id = a.transaction_id
WHERE a.id = $1
FOR UPDATE OF t
`

type GetApprovalForDecideRow struct {
	ID                uuid.UUID          `json:"id"`
	TransactionID     uuid.UUID          `json:"transaction_id"`
	ApproverID        uuid.UUID          `json:"approver_id"`
	ApproverName      string             `json:"approver_name"`
	ApproverEmail     string             `json:"approver_email"`
	ApproverRole      string             `json:"approver_role"`
	Step              int16              `json:"step"`
	ActivatedAt       pgtype.Timestamptz `json:"activated_at"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt         time.Time          `json:"created_at"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	TransactionStatus string             `json:"transaction_status"`
	Description       pgtype.Text        `json:"description"`
	TotalAmount       int64              `json:"total_amount"`
	Currency          string             `json:"currency"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedByName     string             `json:"created_by_name"`
	CreatedByEmail    string             `json:"created_by_email"`
}

func (q *Queries) GetApprovalForDecide(ctx context.Context, id uuid.UUID) (GetApprovalForDecideRow, error) {
	row := q.db.QueryRow(ctx, getApprovalForDecide, id)
	var i GetApprovalForDecideRow
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ApproverID,
		&i.ApproverName,
		&i.ApproverEmail,
		&i.ApproverRole,
		&i.Step,
		&i.ActivatedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.OrganizationID,
		&i.TransactionStatus,
		&i.Description,
		&i.TotalAmount,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByEmail,
	)
	return i, err
}

const listAgingTransactions = `-- name: ListAgingTransactions :many
SELECT t.id, t.description, t.total_amount, t.currency, t.project_id,
       p.name AS project_name, t.submitted_at,
       MIN(a.activated_at)::timestamptz AS waiting_since,
       COUNT(DISTINCT a.approver_id) AS pending_approver_count,
       string_agg(DISTINCT a.approver_name, ', ')::text AS pending_approver_names
FROM approvals a
         JOIN transactions t ON t.id = a.transaction_id
         JOIN projects p ON p.id = t.project_id
WHERE t.organization_id = $1
  AND t.status = 'pending_approval'
  AND t.deleted_at IS NULL
  AND a.activated_at IS NOT NULL
  AND a.cancelled_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM approval_decisions d WHERE d.approval_id = a.id)
  AND a.activated_at <= $2
GROUP BY t.id, p.name
ORDER BY waiting_since ASC
LIMIT $3 OFFSET $4
`

type ListAgingTransactionsParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

type ListAgingTransactionsRow struct {
	ID                   uuid.UUID          `json:"id"`
	Description          pgtype.Text        `json:"description"`
	TotalAmount          int64              `json:"total_amount"`
	Currency             string             `json:"currency"`
	ProjectID            uuid.UUID          `json:"project_id"`
	ProjectName          string             `json:"project_name"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	WaitingSince         time.Time          `json:"waiting_since"`
	PendingApproverCount int64              `json:"pending_approver_count"`
	PendingApproverNames string             `json:"pending_approver_names"`
}

// Pending transactions whose oldest active (undecided) approval step has been
// waiting longer than the cutoff timestamp. One row per transaction.
func (q *Queries) ListAgingTransactions(ctx context.Context, arg ListAgingTransactionsParams) ([]ListAgingTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listAgingTransactions,
		arg.OrganizationID,
		arg.ActivatedAt,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgingTransactionsRow{}
	for rows.Next() {
		var i ListAgingTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.TotalAmount,
			&i.Currency,
			&i.ProjectID,
			&i.ProjectName,
			&i.SubmittedAt,
			&i.WaitingSince,
			&i.PendingApproverCount,
			&i.PendingApproverNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalsByTransaction = `-- name: ListApprovalsByTransaction :many
SELECT id, transaction_id, approver_id, approver_name, approver_email, approver_role,
       step, activated_at, cancelled_at, created_at
FROM approvals
WHERE transaction_id = $1
ORDER BY step ASC, created_at ASC
`

func (q *Queries) ListApprovalsByTransaction(ctx context.Context, transactionID uuid.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovalsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ApproverID,
			&i.ApproverName,
			&i.ApproverEmail,
			&i.ApproverRole,
			&i.Step,
			&i.ActivatedAt,
			&i.CancelledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsByTransaction = `-- name: ListDecisionsByTransaction :many
SELECT d.id, d.approval_id, d.decided_by, d.decided_by_name, d.decided_by_email, d.decided_by_role,
       d.decision, d.notes, d.decided_at
FROM approval_decisions d
         JOIN approvals a ON a.id = d.approval_id
WHERE a.transaction_id = $1
ORDER BY d.decided_at ASC
`

func (q *Queries) ListDecisionsByTransaction(ctx context.Context, transactionID uuid.UUID) ([]ApprovalDecision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalDecision{}
	for rows.Next() {
		var i ApprovalDecision
		if err := rows.Scan(
			&i.ID,
			&i.ApprovalID,
			&i.DecidedBy,
			&i.DecidedByName,
			&i.DecidedByEmail,
			&i.DecidedByRole,
			&i.Decision,
			&i.Notes,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingForUser = `-- name: ListPendingForUser :many
SELECT a.id, a.transaction_id, a.approver_id, a.approver_name, a.approver_email,
       a.approver_role, a.step, a.activated_at, a.cancelled_at, a.created_at,
       t.organization_id, t.status AS transaction_status, t.description, t.total_amount, t.currency,
       t.category, t.created_by, t.created_by_name, t.created_by_email, t.created_by_role,
       t.submitted_at, t.project_id, p.name AS project_name,
       (SELECT COUNT(*) FROM documents d WHERE d.transaction_id = t.id AND d.deleted_at IS NULL) AS document_count
FROM approvals a
         JOIN transactions t ON t.id = a.transaction_id
         JOIN projects p ON p.id = t.project_id
WHERE a.approver_id = $1
  AND t.organization_id = $2
  AND a.activated_at IS NOT NULL
  AND a.cancelled_at IS NULL
  AND t.deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM approval_decisions d WHERE d.approval_id = a.id)
ORDER BY a.activated_at ASC
`

type ListPendingForUserParams struct {
	ApproverID     uuid.UUID `json:"approver_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type ListPendingForUserRow struct {
	ID                uuid.UUID          `json:"id"`
	TransactionID     uuid.UUID          `json:"transaction_id"`
	ApproverID        uuid.UUID          `json:"approver_id"`
	ApproverName      string             `json:"approver_name"`
	ApproverEmail     string             `json:"approver_email"`
	ApproverRole      string             `json:"approver_role"`
	Step              int16              `json:"step"`
	ActivatedAt       pgtype.Timestamptz `json:"activated_at"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt         time.Time          `json:"created_at"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	TransactionStatus string             `json:"transaction_status"`
	Description       pgtype.Text        `json:"description"`
	TotalAmount       int64              `json:"total_amount"`
	Currency          string             `json:"currency"`
	Category          pgtype.Text        `json:"category"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedByName     string             `json:"created_by_name"`
	CreatedByEmail    string             `json:"created_by_email"`
	CreatedByRole     string             `json:"created_by_role"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ProjectID         uuid.UUID          `json:"project_id"`
	ProjectName       string             `json:"project_name"`
	DocumentCount     int64              `json:"document_count"`
}

func (q *Queries) ListPendingForUser(ctx context.Context, arg ListPendingForUserParams) ([]ListPendingForUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingForUser, arg.ApproverID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingForUserRow{}
	for rows.Next() {
		var i ListPendingForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ApproverID,
			&i.ApproverName,
			&i.ApproverEmail,
			&i.ApproverRole,
			&i.Step,
			&i.ActivatedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.OrganizationID,
			&i.TransactionStatus,
			&i.Description,
			&i.TotalAmount,
			&i.Currency,
			&i.Category,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedByEmail,
			&i.CreatedByRole,
			&i.SubmittedAt,
			&i.ProjectID,
			&i.ProjectName,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleActiveApprovals = `-- name: ListStaleActiveApprovals :many
SELECT a.id, a.step, a.activated_at, a.approver_id,
       t.organization_id, t.id AS transaction_id, t.description,
       t.total_amount, t.currency
FROM approvals a
         JOIN transactions t ON t.id = a.transaction_id
WHERE a.activated_at IS NOT NULL
  AND a.cancelled_at IS NULL
  AND t.status = 'pending_approval'
  AND t.deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM approval_decisions d WHERE d.approval_id = a.id)
  AND a.activated_at <= $1
ORDER BY a.activated_at ASC
LIMIT $2
`

type ListStaleActiveApprovalsParams struct {
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	Limit       int32              `json:"limit"`
}

type ListStaleActiveApprovalsRow struct {
	ID             uuid.UUID          `json:"id"`
	Step           int16              `json:"step"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
	ApproverID     uuid.UUID          `json:"approver_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	TransactionID  uuid.UUID          `json:"transaction_id"`
	Description    pgtype.Text        `json:"description"`
	TotalAmount    int64              `json:"total_amount"`
	Currency       string             `json:"currency"`
}

// Active (undecided) approval steps waiting longer than the cutoff, across
// all organizations - the reminder worker's feed.
func (q *Queries) ListStaleActiveApprovals(ctx context.Context, arg ListStaleActiveApprovalsParams) ([]ListStaleActiveApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listStaleActiveApprovals, arg.ActivatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleActiveApprovalsRow{}
	for rows.Next() {
		var i ListStaleActiveApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Step,
			&i.ActivatedAt,
			&i.ApproverID,
			&i.OrganizationID,
			&i.TransactionID,
			&i.Description,
			&i.TotalAmount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
