// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_rules.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countDefaultOrgRules = `-- name: CountDefaultOrgRules :one
SELECT COUNT(*) FROM approval_rules
WHERE organization_id = $1 AND project_id IS NULL AND deleted_at IS NULL
`

func (q *Queries) CountDefaultOrgRules(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDefaultOrgRules, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalRule = `-- name: CreateApprovalRule :one
INSERT INTO approval_rules (organization_id, project_id, approver_id, step, created_by)
VALUES ($1, $2, $3, $4, $5) RETURNING
    id, organization_id, project_id, approver_id, step, created_by, created_at, updated_at, deleted_at
`

type CreateApprovalRuleParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	ProjectID      *uuid.UUID `json:"project_id"`
	ApproverID     uuid.UUID  `json:"approver_id"`
	Step           int16      `json:"step"`
	CreatedBy      uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateApprovalRule(ctx context.Context, arg CreateApprovalRuleParams) (ApprovalRule, error) {
	row := q.db.QueryRow(ctx, createApprovalRule,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ApproverID,
		arg.Step,
		arg.CreatedBy,
	)
	var i ApprovalRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.ApproverID,
		&i.Step,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDefaultApprovalRule = `-- name: CreateDefaultApprovalRule :one
INSERT INTO approval_rules (organization_id, project_id, approver_id, step, created_by)
VALUES ($1, NULL, $2, 1, $2) RETURNING
    id, organization_id, project_id, approver_id, step, created_by, created_at, updated_at, deleted_at
`

type CreateDefaultApprovalRuleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ApproverID     uuid.UUID `json:"approver_id"`
}

func (q *Queries) CreateDefaultApprovalRule(ctx context.Context, arg CreateDefaultApprovalRuleParams) (ApprovalRule, error) {
	row := q.db.QueryRow(ctx, createDefaultApprovalRule, arg.OrganizationID, arg.ApproverID)
	var i ApprovalRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.ApproverID,
		&i.Step,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getApprovalRule = `-- name: GetApprovalRule :one
SELECT id, organization_id, project_id, approver_id, step, created_by, created_at, updated_at, deleted_at
FROM approval_rules
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetApprovalRuleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetApprovalRule(ctx context.Context, arg GetApprovalRuleParams) (ApprovalRule, error) {
	row := q.db.QueryRow(ctx, getApprovalRule, arg.ID, arg.OrganizationID)
	var i ApprovalRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.ApproverID,
		&i.Step,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listApprovalRules = `-- name: ListApprovalRules :many
SELECT id, organization_id, project_id, approver_id, step, created_by, created_at, updated_at, deleted_at
FROM approval_rules
WHERE organization_id = $1 AND deleted_at IS NULL
  AND (
    ($2::uuid IS NOT NULL AND project_id = $2)
        OR ($2::uuid IS NULL AND project_id IS NULL)
  )
ORDER BY step ASC, created_at ASC
`

type ListApprovalRulesParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	ProjectID      *uuid.UUID `json:"project_id"`
}

func (q *Queries) ListApprovalRules(ctx context.Context, arg ListApprovalRulesParams) ([]ApprovalRule, error) {
	rows, err := q.db.Query(ctx, listApprovalRules, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRule{}
	for rows.Next() {
		var i ApprovalRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.ApproverID,
			&i.Step,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByApprover = `-- name: ListRulesByApprover :many
SELECT id, organization_id, project_id, approver_id, step, created_by, created_at, updated_at, deleted_at
FROM approval_rules
WHERE organization_id = $1 AND approver_id = $2 AND deleted_at IS NULL
`

type ListRulesByApproverParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ApproverID     uuid.UUID `json:"approver_id"`
}

func (q *Queries) ListRulesByApprover(ctx context.Context, arg ListRulesByApproverParams) ([]ApprovalRule, error) {
	rows, err := q.db.Query(ctx, listRulesByApprover, arg.OrganizationID, arg.ApproverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRule{}
	for rows.Next() {
		var i ApprovalRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.ApproverID,
			&i.Step,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignApprovalRules = `-- name: ReassignApprovalRules :execrows
UPDATE approval_rules
SET approver_id = $3, updated_at = now()
WHERE organization_id = $1 AND approver_id = $2 AND deleted_at IS NULL
`

type ReassignApprovalRulesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ApproverID     uuid.UUID `json:"approver_id"`
	ApproverID_2   uuid.UUID `json:"approver_id_2"`
}

func (q *Queries) ReassignApprovalRules(ctx context.Context, arg ReassignApprovalRulesParams) (int64, error) {
	result, err := q.db.Exec(ctx, reassignApprovalRules, arg.OrganizationID, arg.ApproverID, arg.ApproverID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveDefaultRules = `-- name: ResolveDefaultRules :many
SELECT id, organization_id, project_id, approver_id, step, created_by, created_at, updated_at, deleted_at
FROM approval_rules
WHERE organization_id = $1 AND project_id IS NULL AND deleted_at IS NULL
ORDER BY step ASC, created_at ASC
`

func (q *Queries) ResolveDefaultRules(ctx context.Context, organizationID uuid.UUID) ([]ApprovalRule, error) {
	rows, err := q.db.Query(ctx, resolveDefaultRules, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRule{}
	for rows.Next() {
		var i ApprovalRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.ApproverID,
			&i.Step,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveProjectRules = `-- name: ResolveProjectRules :many
SELECT id, organization_id, project_id, approver_id, step, created_by, created_at, updated_at, deleted_at
FROM approval_rules
WHERE organization_id = $1 AND project_id = $2 AND deleted_at IS NULL
ORDER BY step ASC, created_at ASC
`

type ResolveProjectRulesParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	ProjectID      *uuid.UUID `json:"project_id"`
}

func (q *Queries) ResolveProjectRules(ctx context.Context, arg ResolveProjectRulesParams) ([]ApprovalRule, error) {
	rows, err := q.db.Query(ctx, resolveProjectRules, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRule{}
	for rows.Next() {
		var i ApprovalRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.ApproverID,
			&i.Step,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteApprovalRule = `-- name: SoftDeleteApprovalRule :execrows
UPDATE approval_rules
SET deleted_at = now()
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type SoftDeleteApprovalRuleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) SoftDeleteApprovalRule(ctx context.Context, arg SoftDeleteApprovalRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteApprovalRule, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateApprovalRuleStep = `-- name: UpdateApprovalRuleStep :one
UPDATE approval_rules
SET step = $3
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL RETURNING
    id, organization_id, project_id, approver_id, step, created_by, created_at, updated_at, deleted_at
`

type UpdateApprovalRuleStepParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Step           int16     `json:"step"`
}

func (q *Queries) UpdateApprovalRuleStep(ctx context.Context, arg UpdateApprovalRuleStepParams) (ApprovalRule, error) {
	row := q.db.QueryRow(ctx, updateApprovalRuleStep, arg.ID, arg.OrganizationID, arg.Step)
	var i ApprovalRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.ApproverID,
		&i.Step,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
