// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachDocumentToTransaction = `-- name: AttachDocumentToTransaction :execrows
UPDATE documents
SET transaction_id = $2, ocr_status = $3, ocr_data = $4, ocr_processed_at = now()
WHERE id = $1 AND ocr_status = 'processing'
`

type AttachDocumentToTransactionParams struct {
	ID            uuid.UUID  `json:"id"`
	TransactionID *uuid.UUID `json:"transaction_id"`
	OcrStatus     string     `json:"ocr_status"`
	OcrData       []byte     `json:"ocr_data"`
}

func (q *Queries) AttachDocumentToTransaction(ctx context.Context, arg AttachDocumentToTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachDocumentToTransaction,
		arg.ID,
		arg.TransactionID,
		arg.OcrStatus,
		arg.OcrData,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDocumentForOCR = `-- name: ClaimDocumentForOCR :execrows
UPDATE documents
SET ocr_status = 'processing'
WHERE id = $1 AND ocr_status = 'pending' AND deleted_at IS NULL
`

// ClaimDocumentForOCR is the consumer's idempotency guard: exactly one
// delivery of document.processed may drive a document out of 'pending', so a
// redelivered event claims zero rows and is skipped instead of creating a
// second draft transaction.
func (q *Queries) ClaimDocumentForOCR(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimDocumentForOCR, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeDocumentOCR = `-- name: CompleteDocumentOCR :execrows
UPDATE documents
SET ocr_status = $2, ocr_data = $3, ocr_processed_at = now()
WHERE id = $1 AND ocr_status = 'processing'
`

type CompleteDocumentOCRParams struct {
	ID        uuid.UUID `json:"id"`
	OcrStatus string    `json:"ocr_status"`
	OcrData   []byte    `json:"ocr_data"`
}

func (q *Queries) CompleteDocumentOCR(ctx context.Context, arg CompleteDocumentOCRParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeDocumentOCR, arg.ID, arg.OcrStatus, arg.OcrData)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (project_id, transaction_id, storage_path, file_name, file_size,
                       mime_type, file_hash, uploaded_by, uploaded_by_name, uploaded_by_email, uploaded_by_role)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING
    id, project_id, transaction_id, storage_path, file_name, file_size, mime_type, file_hash,
    ocr_status, ocr_data, ocr_processed_at, uploaded_by, uploaded_by_name, uploaded_by_email,
    uploaded_by_role, created_at, deleted_at
`

type CreateDocumentParams struct {
	ProjectID       uuid.UUID   `json:"project_id"`
	TransactionID   *uuid.UUID  `json:"transaction_id"`
	StoragePath     string      `json:"storage_path"`
	FileName        string      `json:"file_name"`
	FileSize        int64       `json:"file_size"`
	MimeType        string      `json:"mime_type"`
	FileHash        pgtype.Text `json:"file_hash"`
	UploadedBy      uuid.UUID   `json:"uploaded_by"`
	UploadedByName  string      `json:"uploaded_by_name"`
	UploadedByEmail string      `json:"uploaded_by_email"`
	UploadedByRole  string      `json:"uploaded_by_role"`
}

type CreateDocumentRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	TransactionID   *uuid.UUID         `json:"transaction_id"`
	StoragePath     string             `json:"storage_path"`
	FileName        string             `json:"file_name"`
	FileSize        int64              `json:"file_size"`
	MimeType        string             `json:"mime_type"`
	FileHash        pgtype.Text        `json:"file_hash"`
	OcrStatus       string             `json:"ocr_status"`
	OcrData         []byte             `json:"ocr_data"`
	OcrProcessedAt  pgtype.Timestamptz `json:"ocr_processed_at"`
	UploadedBy      uuid.UUID          `json:"uploaded_by"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByEmail string             `json:"uploaded_by_email"`
	UploadedByRole  string             `json:"uploaded_by_role"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ProjectID,
		arg.TransactionID,
		arg.StoragePath,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.FileHash,
		arg.UploadedBy,
		arg.UploadedByName,
		arg.UploadedByEmail,
		arg.UploadedByRole,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TransactionID,
		&i.StoragePath,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.FileHash,
		&i.OcrStatus,
		&i.OcrData,
		&i.OcrProcessedAt,
		&i.UploadedBy,
		&i.UploadedByName,
		&i.UploadedByEmail,
		&i.UploadedByRole,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const failDocumentOCR = `-- name: FailDocumentOCR :execrows
UPDATE documents
SET ocr_status = 'failed', ocr_processed_at = now()
WHERE id = $1 AND ocr_status = 'processing'
`

func (q *Queries) FailDocumentOCR(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, failDocumentOCR, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT d.id, d.project_id, d.transaction_id, d.storage_path, d.file_name, d.file_size,
       d.mime_type, d.file_hash, d.ocr_status, d.ocr_data, d.ocr_processed_at,
       d.uploaded_by, d.uploaded_by_name, d.uploaded_by_email, d.uploaded_by_role,
       d.created_at, d.deleted_at
FROM documents d
         JOIN projects p ON p.id = d.project_id
WHERE d.id = $1 AND p.organization_id = $2 AND d.deleted_at IS NULL
`

type GetDocumentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetDocumentRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	TransactionID   *uuid.UUID         `json:"transaction_id"`
	StoragePath     string             `json:"storage_path"`
	FileName        string             `json:"file_name"`
	FileSize        int64              `json:"file_size"`
	MimeType        string             `json:"mime_type"`
	FileHash        pgtype.Text        `json:"file_hash"`
	OcrStatus       string             `json:"ocr_status"`
	OcrData         []byte             `json:"ocr_data"`
	OcrProcessedAt  pgtype.Timestamptz `json:"ocr_processed_at"`
	UploadedBy      uuid.UUID          `json:"uploaded_by"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByEmail string             `json:"uploaded_by_email"`
	UploadedByRole  string             `json:"uploaded_by_role"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.OrganizationID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TransactionID,
		&i.StoragePath,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.FileHash,
		&i.OcrStatus,
		&i.OcrData,
		&i.OcrProcessedAt,
		&i.UploadedBy,
		&i.UploadedByName,
		&i.UploadedByEmail,
		&i.UploadedByRole,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentForProcessing = `-- name: GetDocumentForProcessing :one
SELECT d.id, d.project_id, d.transaction_id, d.storage_path, d.file_name, d.file_size,
       d.mime_type, d.file_hash, d.ocr_status, d.ocr_data, d.ocr_processed_at,
       d.uploaded_by, d.uploaded_by_name, d.uploaded_by_email, d.uploaded_by_role,
       d.created_at, d.deleted_at,
       p.organization_id
FROM documents d
         JOIN projects p ON p.id = d.project_id
WHERE d.id = $1 AND d.deleted_at IS NULL
`

type GetDocumentForProcessingRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	TransactionID   *uuid.UUID         `json:"transaction_id"`
	StoragePath     string             `json:"storage_path"`
	FileName        string             `json:"file_name"`
	FileSize        int64              `json:"file_size"`
	MimeType        string             `json:"mime_type"`
	FileHash        pgtype.Text        `json:"file_hash"`
	OcrStatus       string             `json:"ocr_status"`
	OcrData         []byte             `json:"ocr_data"`
	OcrProcessedAt  pgtype.Timestamptz `json:"ocr_processed_at"`
	UploadedBy      uuid.UUID          `json:"uploaded_by"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByEmail string             `json:"uploaded_by_email"`
	UploadedByRole  string             `json:"uploaded_by_role"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
}

func (q *Queries) GetDocumentForProcessing(ctx context.Context, id uuid.UUID) (GetDocumentForProcessingRow, error) {
	row := q.db.QueryRow(ctx, getDocumentForProcessing, id)
	var i GetDocumentForProcessingRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TransactionID,
		&i.StoragePath,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.FileHash,
		&i.OcrStatus,
		&i.OcrData,
		&i.OcrProcessedAt,
		&i.UploadedBy,
		&i.UploadedByName,
		&i.UploadedByEmail,
		&i.UploadedByRole,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listDocumentsByProject = `-- name: ListDocumentsByProject :many
SELECT id, project_id, transaction_id, storage_path, file_name, file_size, mime_type, file_hash,
       ocr_status, ocr_data, ocr_processed_at, uploaded_by, uploaded_by_name, uploaded_by_email,
       uploaded_by_role, created_at, deleted_at
FROM documents
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListDocumentsByProjectRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	TransactionID   *uuid.UUID         `json:"transaction_id"`
	StoragePath     string             `json:"storage_path"`
	FileName        string             `json:"file_name"`
	FileSize        int64              `json:"file_size"`
	MimeType        string             `json:"mime_type"`
	FileHash        pgtype.Text        `json:"file_hash"`
	OcrStatus       string             `json:"ocr_status"`
	OcrData         []byte             `json:"ocr_data"`
	OcrProcessedAt  pgtype.Timestamptz `json:"ocr_processed_at"`
	UploadedBy      uuid.UUID          `json:"uploaded_by"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByEmail string             `json:"uploaded_by_email"`
	UploadedByRole  string             `json:"uploaded_by_role"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDocumentsByProject(ctx context.Context, projectID uuid.UUID) ([]ListDocumentsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByProjectRow{}
	for rows.Next() {
		var i ListDocumentsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TransactionID,
			&i.StoragePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.FileHash,
			&i.OcrStatus,
			&i.OcrData,
			&i.OcrProcessedAt,
			&i.UploadedBy,
			&i.UploadedByName,
			&i.UploadedByEmail,
			&i.UploadedByRole,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTransaction = `-- name: ListDocumentsByTransaction :many
SELECT id, project_id, transaction_id, storage_path, file_name, file_size, mime_type, file_hash,
       ocr_status, ocr_data, ocr_processed_at, uploaded_by, uploaded_by_name, uploaded_by_email,
       uploaded_by_role, created_at, deleted_at
FROM documents
WHERE transaction_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListDocumentsByTransactionRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	TransactionID   *uuid.UUID         `json:"transaction_id"`
	StoragePath     string             `json:"storage_path"`
	FileName        string             `json:"file_name"`
	FileSize        int64              `json:"file_size"`
	MimeType        string             `json:"mime_type"`
	FileHash        pgtype.Text        `json:"file_hash"`
	OcrStatus       string             `json:"ocr_status"`
	OcrData         []byte             `json:"ocr_data"`
	OcrProcessedAt  pgtype.Timestamptz `json:"ocr_processed_at"`
	UploadedBy      uuid.UUID          `json:"uploaded_by"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByEmail string             `json:"uploaded_by_email"`
	UploadedByRole  string             `json:"uploaded_by_role"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDocumentsByTransaction(ctx context.Context, transactionID *uuid.UUID) ([]ListDocumentsByTransactionRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByTransactionRow{}
	for rows.Next() {
		var i ListDocumentsByTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TransactionID,
			&i.StoragePath,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.FileHash,
			&i.OcrStatus,
			&i.OcrData,
			&i.OcrProcessedAt,
			&i.UploadedBy,
			&i.UploadedByName,
			&i.UploadedByEmail,
			&i.UploadedByRole,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOCRDocuments = `-- name: ListStaleOCRDocuments :many
SELECT id, ocr_document_id
FROM documents
WHERE deleted_at IS NULL
  AND ocr_status IN ('pending', 'processing')
  AND ocr_document_id IS NOT NULL
  AND created_at < $1
ORDER BY created_at
LIMIT $2
`

type ListStaleOCRDocumentsParams struct {
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

type ListStaleOCRDocumentsRow struct {
	ID            uuid.UUID  `json:"id"`
	OcrDocumentID *uuid.UUID `json:"ocr_document_id"`
}

// Documents still waiting on OCR past the sweep threshold that have a job id
// to ask about. Rows without ocr_document_id predate submit-response storage
// and can only be resolved by the routed event.
func (q *Queries) ListStaleOCRDocuments(ctx context.Context, arg ListStaleOCRDocumentsParams) ([]ListStaleOCRDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listStaleOCRDocuments, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleOCRDocumentsRow{}
	for rows.Next() {
		var i ListStaleOCRDocumentsRow
		if err := rows.Scan(&i.ID, &i.OcrDocumentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOcrDocumentID = `-- name: SetOcrDocumentID :execrows
UPDATE documents
SET ocr_document_id = $2
WHERE id = $1
  AND ocr_document_id IS NULL
`

type SetOcrDocumentIDParams struct {
	ID            uuid.UUID  `json:"id"`
	OcrDocumentID *uuid.UUID `json:"ocr_document_id"`
}

// Stores the ocr job id returned at submit time, so the reconciliation sweep
// can ask the gateway about documents whose routed event never arrived.
func (q *Queries) SetOcrDocumentID(ctx context.Context, arg SetOcrDocumentIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOcrDocumentID, arg.ID, arg.OcrDocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :execrows
UPDATE documents
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
