// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	ID            uuid.UUID          `json:"id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	ApproverID    uuid.UUID          `json:"approver_id"`
	ApproverName  string             `json:"approver_name"`
	ApproverEmail string             `json:"approver_email"`
	ApproverRole  string             `json:"approver_role"`
	Step          int16              `json:"step"`
	ActivatedAt   pgtype.Timestamptz `json:"activated_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type ApprovalDecision struct {
	ID             uuid.UUID   `json:"id"`
	ApprovalID     uuid.UUID   `json:"approval_id"`
	DecidedBy      uuid.UUID   `json:"decided_by"`
	DecidedByName  string      `json:"decided_by_name"`
	DecidedByEmail string      `json:"decided_by_email"`
	DecidedByRole  string      `json:"decided_by_role"`
	Decision       string      `json:"decision"`
	Notes          pgtype.Text `json:"notes"`
	DecidedAt      time.Time   `json:"decided_at"`
}

type ApprovalRule struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProjectID      *uuid.UUID         `json:"project_id"`
	ApproverID     uuid.UUID          `json:"approver_id"`
	Step           int16              `json:"step"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Document struct {
	ID              uuid.UUID          `json:"id"`
	TransactionID   *uuid.UUID         `json:"transaction_id"`
	StoragePath     string             `json:"storage_path"`
	FileName        string             `json:"file_name"`
	FileSize        int64              `json:"file_size"`
	MimeType        string             `json:"mime_type"`
	FileHash        pgtype.Text        `json:"file_hash"`
	OcrStatus       string             `json:"ocr_status"`
	OcrData         []byte             `json:"ocr_data"`
	OcrProcessedAt  pgtype.Timestamptz `json:"ocr_processed_at"`
	UploadedBy      uuid.UUID          `json:"uploaded_by"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	ProjectID       uuid.UUID          `json:"project_id"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByEmail string             `json:"uploaded_by_email"`
	UploadedByRole  string             `json:"uploaded_by_role"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Topic         string             `json:"topic"`
	Payload       []byte             `json:"payload"`
	CreatedAt     time.Time          `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	TraceID       pgtype.Text        `json:"trace_id"`
	AttemptCount  int32              `json:"attempt_count"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	LastError     pgtype.Text        `json:"last_error"`
}

type Project struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
}

type ProjectMember struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	UserID         uuid.UUID `json:"user_id"`
	RoleID         uuid.UUID `json:"role_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Role struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	IsSystem  bool               `json:"is_system"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type RolePermission struct {
	RoleID uuid.UUID `json:"role_id"`
	Action string    `json:"action"`
}

type Transaction struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Status         string             `json:"status"`
	Description    pgtype.Text        `json:"description"`
	TotalAmount    int64              `json:"total_amount"`
	Currency       string             `json:"currency"`
	Category       pgtype.Text        `json:"category"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedByName  string             `json:"created_by_name"`
	CreatedByEmail string             `json:"created_by_email"`
	CreatedByRole  string             `json:"created_by_role"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type TransactionItem struct {
	ID            uuid.UUID `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	Description   string    `json:"description"`
	Quantity      int32     `json:"quantity"`
	Amount        int64     `json:"amount"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
