// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveProject = `-- name: ArchiveProject :one
UPDATE projects
SET archived_at = now()
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL AND archived_at IS NULL RETURNING
    id, organization_id, name, created_by, created_at, updated_at, deleted_at, archived_at
`

type ArchiveProjectParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, archiveProject, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const countProjectTransactions = `-- name: CountProjectTransactions :one
SELECT COUNT(*) FROM transactions WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectTransactions(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectTransactions, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id, name, created_by)
VALUES ($1, $2, $3) RETURNING
    id, organization_id, name, created_by, created_at, updated_at, deleted_at, archived_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	CreatedBy      uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrganizationID, arg.Name, arg.CreatedBy)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteProjectMember = `-- name: DeleteProjectMember :execrows
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type DeleteProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, organization_id, name, created_by, created_at, updated_at, deleted_at, archived_at
FROM projects
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetProjectParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT organization_id, project_id, user_id, role_id, created_at, updated_at
FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlacedProjects = `-- name: ListPlacedProjects :many
SELECT p.id, p.organization_id, p.name, p.created_by, p.created_at, p.updated_at, p.deleted_at, p.archived_at
FROM projects p
         JOIN project_members pm ON pm.project_id = p.id
WHERE p.organization_id = $1 AND pm.user_id = $2 AND p.deleted_at IS NULL
  AND ($3::bool OR p.archived_at IS NULL)
ORDER BY p.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPlacedProjectsParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	UserID          uuid.UUID `json:"user_id"`
	IncludeArchived bool      `json:"include_archived"`
	Offset          int32     `json:"offset"`
	Limit           int32     `json:"limit"`
}

func (q *Queries) ListPlacedProjects(ctx context.Context, arg ListPlacedProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listPlacedProjects,
		arg.OrganizationID,
		arg.UserID,
		arg.IncludeArchived,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.organization_id, pm.project_id, pm.user_id, pm.role_id, pm.created_at, pm.updated_at,
       r.name AS role_name, r.is_system AS role_is_system
FROM project_members pm
         JOIN roles r ON r.id = pm.role_id AND r.deleted_at IS NULL
WHERE pm.project_id = $1
ORDER BY pm.created_at ASC
`

type ListProjectMembersRow struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	UserID         uuid.UUID `json:"user_id"`
	RoleID         uuid.UUID `json:"role_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	RoleName       string    `json:"role_name"`
	RoleIsSystem   bool      `json:"role_is_system"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ProjectID,
			&i.UserID,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
			&i.RoleIsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, organization_id, name, created_by, created_at, updated_at, deleted_at, archived_at
FROM projects
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::bool OR archived_at IS NULL)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListProjectsParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	IncludeArchived bool      `json:"include_archived"`
	Offset          int32     `json:"offset"`
	Limit           int32     `json:"limit"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.OrganizationID,
		arg.IncludeArchived,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE projects
SET deleted_at = now()
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unarchiveProject = `-- name: UnarchiveProject :one
UPDATE projects
SET archived_at = NULL
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL AND archived_at IS NOT NULL RETURNING
    id, organization_id, name, created_by, created_at, updated_at, deleted_at, archived_at
`

type UnarchiveProjectParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UnarchiveProject(ctx context.Context, arg UnarchiveProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, unarchiveProject, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateProjectName = `-- name: UpdateProjectName :one
UPDATE projects
SET name = $2
WHERE id = $1 AND organization_id = $3 AND deleted_at IS NULL RETURNING
    id, organization_id, name, created_by, created_at, updated_at, deleted_at, archived_at
`

type UpdateProjectNameParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectName, arg.ID, arg.Name, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertProjectMember = `-- name: UpsertProjectMember :one
INSERT INTO project_members (organization_id, project_id, user_id, role_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, user_id)
    DO UPDATE SET role_id = EXCLUDED.role_id RETURNING
        organization_id, project_id, user_id, role_id, created_at, updated_at
`

type UpsertProjectMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	UserID         uuid.UUID `json:"user_id"`
	RoleID         uuid.UUID `json:"role_id"`
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, upsertProjectMember,
		arg.OrganizationID,
		arg.ProjectID,
		arg.UserID,
		arg.RoleID,
	)
	var i ProjectMember
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
