// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateApprovalStep(ctx context.Context, arg ActivateApprovalStepParams) (int64, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	ApprovalHasDecision(ctx context.Context, approvalID uuid.UUID) (bool, error)
	ApproveTransaction(ctx context.Context, id uuid.UUID) (int64, error)
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error)
	AttachDocumentToTransaction(ctx context.Context, arg AttachDocumentToTransactionParams) (int64, error)
	CancelPendingApprovals(ctx context.Context, transactionID uuid.UUID) (int64, error)
	// ClaimDocumentForOCR is the consumer's idempotency guard: exactly one
	// delivery of document.processed may drive a document out of 'pending', so a
	// redelivered event claims zero rows and is skipped instead of creating a
	// second draft transaction.
	ClaimDocumentForOCR(ctx context.Context, id uuid.UUID) (int64, error)
	ClaimPendingOutboxEvents(ctx context.Context, arg ClaimPendingOutboxEventsParams) ([]OutboxEvent, error)
	CompleteDocumentOCR(ctx context.Context, arg CompleteDocumentOCRParams) (int64, error)
	CountDefaultOrgRules(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountProjectTransactions(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountRoleUsage(ctx context.Context, roleID uuid.UUID) (int64, error)
	CountTransactionDocuments(ctx context.Context, transactionID *uuid.UUID) (int64, error)
	CreateApproval(ctx context.Context, arg CreateApprovalParams) error
	CreateApprovalDecision(ctx context.Context, arg CreateApprovalDecisionParams) (ApprovalDecision, error)
	CreateApprovalRule(ctx context.Context, arg CreateApprovalRuleParams) (ApprovalRule, error)
	CreateDefaultApprovalRule(ctx context.Context, arg CreateDefaultApprovalRuleParams) (ApprovalRule, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) (int64, error)
	DeletePublishedOutboxEvents(ctx context.Context) (int64, error)
	DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error
	DeleteTransactionItems(ctx context.Context, transactionID uuid.UUID) (int64, error)
	FailDocumentOCR(ctx context.Context, id uuid.UUID) (int64, error)
	GetApprovalForDecide(ctx context.Context, id uuid.UUID) (GetApprovalForDecideRow, error)
	GetApprovalRule(ctx context.Context, arg GetApprovalRuleParams) (ApprovalRule, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error)
	GetDocumentForProcessing(ctx context.Context, id uuid.UUID) (GetDocumentForProcessingRow, error)
	GetOldestPendingOutboxAgeSeconds(ctx context.Context) (int64, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error)
	GetRole(ctx context.Context, arg GetRoleParams) (Role, error)
	GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	GetUserProjectActions(ctx context.Context, arg GetUserProjectActionsParams) ([]string, error)
	InsertTransactionItems(ctx context.Context, arg InsertTransactionItemsParams) (int64, error)
	ListActivePlacementsWithAction(ctx context.Context, arg ListActivePlacementsWithActionParams) ([]uuid.UUID, error)
	// Pending transactions whose oldest active (undecided) approval step has been
	// waiting longer than the cutoff timestamp. One row per transaction.
	ListAgingTransactions(ctx context.Context, arg ListAgingTransactionsParams) ([]ListAgingTransactionsRow, error)
	ListApprovalRules(ctx context.Context, arg ListApprovalRulesParams) ([]ApprovalRule, error)
	ListApprovalsByTransaction(ctx context.Context, transactionID uuid.UUID) ([]Approval, error)
	ListDecisionsByTransaction(ctx context.Context, transactionID uuid.UUID) ([]ApprovalDecision, error)
	ListDocumentsByProject(ctx context.Context, projectID uuid.UUID) ([]ListDocumentsByProjectRow, error)
	ListDocumentsByTransaction(ctx context.Context, transactionID *uuid.UUID) ([]ListDocumentsByTransactionRow, error)
	ListPendingForUser(ctx context.Context, arg ListPendingForUserParams) ([]ListPendingForUserRow, error)
	ListPlacedProjects(ctx context.Context, arg ListPlacedProjectsParams) ([]Project, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListRoleActions(ctx context.Context, roleID uuid.UUID) ([]string, error)
	ListRoleUsageProjects(ctx context.Context, roleID uuid.UUID) ([]ListRoleUsageProjectsRow, error)
	ListRoles(ctx context.Context, projectID uuid.UUID) ([]Role, error)
	ListRulesByApprover(ctx context.Context, arg ListRulesByApproverParams) ([]ApprovalRule, error)
	// Active (undecided) approval steps waiting longer than the cutoff, across
	// all organizations - the reminder worker's feed.
	ListStaleActiveApprovals(ctx context.Context, arg ListStaleActiveApprovalsParams) ([]ListStaleActiveApprovalsRow, error)
	// Documents still waiting on OCR past the sweep threshold that have a job id
	// to ask about. Rows without ocr_document_id predate submit-response storage
	// and can only be resolved by the routed event.
	ListStaleOCRDocuments(ctx context.Context, arg ListStaleOCRDocumentsParams) ([]ListStaleOCRDocumentsRow, error)
	ListTransactionItems(ctx context.Context, transactionID uuid.UUID) ([]TransactionItem, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error)
	LockTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
	ReassignApprovalRules(ctx context.Context, arg ReassignApprovalRulesParams) (int64, error)
	RejectTransaction(ctx context.Context, id uuid.UUID) (int64, error)
	ReleaseOutboxEventLock(ctx context.Context, id uuid.UUID) error
	ResolveDefaultRules(ctx context.Context, organizationID uuid.UUID) ([]ApprovalRule, error)
	ResolveProjectRules(ctx context.Context, arg ResolveProjectRulesParams) ([]ApprovalRule, error)
	// Stores the ocr job id returned at submit time, so the reconciliation sweep
	// can ask the gateway about documents whose routed event never arrived.
	SetOcrDocumentID(ctx context.Context, arg SetOcrDocumentIDParams) (int64, error)
	SoftDeleteApprovalRule(ctx context.Context, arg SoftDeleteApprovalRuleParams) (int64, error)
	SoftDeleteDocument(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error)
	SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) (int64, error)
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error)
	SubmitTransaction(ctx context.Context, id uuid.UUID) (int64, error)
	UnarchiveProject(ctx context.Context, arg UnarchiveProjectParams) (Project, error)
	UpdateApprovalRuleStep(ctx context.Context, arg UpdateApprovalRuleStepParams) (ApprovalRule, error)
	UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error)
	UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) (Role, error)
	UpdateTransactionDraft(ctx context.Context, arg UpdateTransactionDraftParams) (Transaction, error)
	UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) (ProjectMember, error)
}

var _ Querier = (*Queries)(nil)
