// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, action) VALUES ($1, $2)
ON CONFLICT (role_id, action) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID uuid.UUID `json:"role_id"`
	Action string    `json:"action"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.Action)
	return err
}

const countRoleUsage = `-- name: CountRoleUsage :one
SELECT COUNT(*) FROM project_members WHERE role_id = $1
`

func (q *Queries) CountRoleUsage(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleUsage, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (project_id, name, is_system, created_by)
VALUES ($1, $2, $3, $4) RETURNING
    id, project_id, name, is_system, created_by, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
	IsSystem  bool      `json:"is_system"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ProjectID,
		arg.Name,
		arg.IsSystem,
		arg.CreatedBy,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, project_id, name, is_system, created_by, created_at, updated_at, deleted_at
FROM roles
WHERE id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type GetRoleParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ID, arg.ProjectID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, project_id, name, is_system, created_by, created_at, updated_at, deleted_at
FROM roles
WHERE project_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetRoleByNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.ProjectID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserProjectActions = `-- name: GetUserProjectActions :many
SELECT DISTINCT rp.action
FROM project_members pm
         JOIN role_permissions rp ON rp.role_id = pm.role_id
         JOIN roles r ON r.id = pm.role_id AND r.deleted_at IS NULL
WHERE pm.project_id = $1 AND pm.user_id = $2
`

type GetUserProjectActionsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserProjectActions(ctx context.Context, arg GetUserProjectActionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserProjectActions, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePlacementsWithAction = `-- name: ListActivePlacementsWithAction :many
SELECT pm.project_id
FROM project_members pm
         JOIN role_permissions rp ON rp.role_id = pm.role_id
         JOIN roles r ON r.id = pm.role_id AND r.deleted_at IS NULL
WHERE pm.organization_id = $1 AND pm.user_id = $2 AND rp.action = $3
`

type ListActivePlacementsWithActionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Action         string    `json:"action"`
}

func (q *Queries) ListActivePlacementsWithAction(ctx context.Context, arg ListActivePlacementsWithActionParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActivePlacementsWithAction, arg.OrganizationID, arg.UserID, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var project_id uuid.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleActions = `-- name: ListRoleActions :many
SELECT action FROM role_permissions WHERE role_id = $1 ORDER BY action
`

func (q *Queries) ListRoleActions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleActions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleUsageProjects = `-- name: ListRoleUsageProjects :many
SELECT p.id, p.name
FROM project_members pm
         JOIN projects p ON p.id = pm.project_id
WHERE pm.role_id = $1 AND p.deleted_at IS NULL
ORDER BY p.name
`

type ListRoleUsageProjectsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListRoleUsageProjects(ctx context.Context, roleID uuid.UUID) ([]ListRoleUsageProjectsRow, error) {
	rows, err := q.db.Query(ctx, listRoleUsageProjects, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleUsageProjectsRow{}
	for rows.Next() {
		var i ListRoleUsageProjectsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, project_id, name, is_system, created_by, created_at, updated_at, deleted_at
FROM roles
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListRoles(ctx context.Context, projectID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IsSystem,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :execrows
UPDATE roles
SET deleted_at = now()
WHERE id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type SoftDeleteRoleParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteRole, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRoleName = `-- name: UpdateRoleName :one
UPDATE roles
SET name = $2
WHERE id = $1 AND project_id = $3 AND deleted_at IS NULL RETURNING
    id, project_id, name, is_system, created_by, created_at, updated_at, deleted_at
`

type UpdateRoleNameParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRoleName, arg.ID, arg.Name, arg.ProjectID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
