// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction_items.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const deleteTransactionItems = `-- name: DeleteTransactionItems :execrows
DELETE FROM transaction_items WHERE transaction_id = $1
`

func (q *Queries) DeleteTransactionItems(ctx context.Context, transactionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransactionItems, transactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTransactionItems = `-- name: InsertTransactionItems :execrows
INSERT INTO transaction_items (transaction_id, description, quantity, amount)
SELECT $1,
       unnest($2::text[]),
       unnest($3::int[]),
       unnest($4::bigint[])
`

type InsertTransactionItemsParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	Descriptions  []string  `json:"descriptions"`
	Quantities    []int32   `json:"quantities"`
	Amounts       []int64   `json:"amounts"`
}

func (q *Queries) InsertTransactionItems(ctx context.Context, arg InsertTransactionItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTransactionItems,
		arg.TransactionID,
		arg.Descriptions,
		arg.Quantities,
		arg.Amounts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTransactionItems = `-- name: ListTransactionItems :many
SELECT id, transaction_id, description, quantity, amount, created_at, updated_at
FROM transaction_items
WHERE transaction_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListTransactionItems(ctx context.Context, transactionID uuid.UUID) ([]TransactionItem, error) {
	rows, err := q.db.Query(ctx, listTransactionItems, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionItem{}
	for rows.Next() {
		var i TransactionItem
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Description,
			&i.Quantity,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
