// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveTransaction = `-- name: ApproveTransaction :execrows
UPDATE transactions
SET status = 'approved', decided_at = now()
WHERE id = $1 AND status = 'pending_approval'
`

func (q *Queries) ApproveTransaction(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, approveTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countTransactionDocuments = `-- name: CountTransactionDocuments :one
SELECT COUNT(*) FROM documents WHERE transaction_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTransactionDocuments(ctx context.Context, transactionID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionDocuments, transactionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (organization_id, project_id, description, currency,
                          category, created_by, created_by_name, created_by_email, created_by_role)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING
    id, organization_id, project_id, status, description, total_amount, currency, category,
    created_by, created_by_name, created_by_email, created_by_role,
    submitted_at, decided_at, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ProjectID      uuid.UUID   `json:"project_id"`
	Description    pgtype.Text `json:"description"`
	Currency       string      `json:"currency"`
	Category       pgtype.Text `json:"category"`
	CreatedBy      uuid.UUID   `json:"created_by"`
	CreatedByName  string      `json:"created_by_name"`
	CreatedByEmail string      `json:"created_by_email"`
	CreatedByRole  string      `json:"created_by_role"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Description,
		arg.Currency,
		arg.Category,
		arg.CreatedBy,
		arg.CreatedByName,
		arg.CreatedByEmail,
		arg.CreatedByRole,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Status,
		&i.Description,
		&i.TotalAmount,
		&i.Currency,
		&i.Category,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByEmail,
		&i.CreatedByRole,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, organization_id, project_id, status, description, total_amount, currency, category,
       created_by, created_by_name, created_by_email, created_by_role,
       submitted_at, decided_at, created_at, updated_at, deleted_at
FROM transactions
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetTransactionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.OrganizationID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Status,
		&i.Description,
		&i.TotalAmount,
		&i.Currency,
		&i.Category,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByEmail,
		&i.CreatedByRole,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.organization_id, t.project_id, t.status, t.description, t.total_amount, t.currency,
       t.category, t.created_by, t.created_by_name, t.created_by_email, t.created_by_role,
       t.submitted_at, t.decided_at, t.created_at, t.updated_at,
       p.name AS project_name,
       (SELECT COUNT(*) FROM documents d WHERE d.transaction_id = t.id AND d.deleted_at IS NULL) AS document_count,
       (SELECT COUNT(*) FROM approvals a WHERE a.transaction_id = t.id)                          AS total_steps,
       (SELECT MIN(a.step) FROM approvals a
        WHERE a.transaction_id = t.id AND a.activated_at IS NOT NULL AND a.cancelled_at IS NULL
          AND NOT EXISTS (SELECT 1 FROM approval_decisions ad WHERE ad.approval_id = a.id))      AS current_step,
       (SELECT COALESCE(json_agg(json_build_object('id', w.approver_id, 'name', w.approver_name)), '[]'::json)
        FROM approvals w
        WHERE w.transaction_id = t.id AND w.activated_at IS NOT NULL AND w.cancelled_at IS NULL
          AND NOT EXISTS (SELECT 1 FROM approval_decisions ad WHERE ad.approval_id = w.id))      AS waiting_for
FROM transactions t
         JOIN projects p ON p.id = t.project_id
WHERE t.organization_id = $1 AND t.deleted_at IS NULL
  AND ($2::uuid[] IS NULL OR t.project_id = ANY($2))
  AND ($3::text IS NULL OR t.status = $3)
  AND ($4::uuid IS NULL OR t.project_id = $4)
  AND ($5::uuid IS NULL OR t.created_by = $5)
  AND ($6::text IS NULL OR t.category = $6)
  AND ($7::timestamptz IS NULL OR t.created_at >= $7)
  AND ($8::timestamptz IS NULL OR t.created_at <= $8)
ORDER BY t.created_at DESC
LIMIT $10 OFFSET $9
`

type ListTransactionsParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProjectIds     []uuid.UUID        `json:"project_ids"`
	Status         pgtype.Text        `json:"status"`
	ProjectID      *uuid.UUID         `json:"project_id"`
	CreatedBy      *uuid.UUID         `json:"created_by"`
	Category       pgtype.Text        `json:"category"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
	Offset         int32              `json:"offset"`
	Limit          int32              `json:"limit"`
}

type ListTransactionsRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Status         string             `json:"status"`
	Description    pgtype.Text        `json:"description"`
	TotalAmount    int64              `json:"total_amount"`
	Currency       string             `json:"currency"`
	Category       pgtype.Text        `json:"category"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedByName  string             `json:"created_by_name"`
	CreatedByEmail string             `json:"created_by_email"`
	CreatedByRole  string             `json:"created_by_role"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	ProjectName    string             `json:"project_name"`
	DocumentCount  int64              `json:"document_count"`
	TotalSteps     int64              `json:"total_steps"`
	CurrentStep    interface{}        `json:"current_step"`
	WaitingFor     interface{}        `json:"waiting_for"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.OrganizationID,
		arg.ProjectIds,
		arg.Status,
		arg.ProjectID,
		arg.CreatedBy,
		arg.Category,
		arg.DateFrom,
		arg.DateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Status,
			&i.Description,
			&i.TotalAmount,
			&i.Currency,
			&i.Category,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedByEmail,
			&i.CreatedByRole,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.DocumentCount,
			&i.TotalSteps,
			&i.CurrentStep,
			&i.WaitingFor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTransaction = `-- name: LockTransaction :one
SELECT id, organization_id, project_id, status, description, total_amount, currency, category,
       created_by, created_by_name, created_by_email, created_by_role,
       submitted_at, decided_at, created_at, updated_at, deleted_at
FROM transactions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, lockTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Status,
		&i.Description,
		&i.TotalAmount,
		&i.Currency,
		&i.Category,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByEmail,
		&i.CreatedByRole,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const rejectTransaction = `-- name: RejectTransaction :execrows
UPDATE transactions
SET status = 'rejected', decided_at = now()
WHERE id = $1 AND status = 'pending_approval'
`

func (q *Queries) RejectTransaction(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, rejectTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :execrows
UPDATE transactions
SET deleted_at = now()
WHERE id = $1 AND organization_id = $2 AND status = 'draft' AND deleted_at IS NULL
`

type SoftDeleteTransactionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransaction, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const submitTransaction = `-- name: SubmitTransaction :execrows
UPDATE transactions
SET status = 'pending_approval', submitted_at = now()
WHERE id = $1 AND status = 'draft' AND deleted_at IS NULL
`

func (q *Queries) SubmitTransaction(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, submitTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransactionDraft = `-- name: UpdateTransactionDraft :one
UPDATE transactions
SET description = $3, currency = $4, category = $5
WHERE id = $1 AND organization_id = $2 AND status = 'draft' AND deleted_at IS NULL RETURNING
    id, organization_id, project_id, status, description, total_amount, currency, category,
    created_by, created_by_name, created_by_email, created_by_role,
    submitted_at, decided_at, created_at, updated_at, deleted_at
`

type UpdateTransactionDraftParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Description    pgtype.Text `json:"description"`
	Currency       string      `json:"currency"`
	Category       pgtype.Text `json:"category"`
}

func (q *Queries) UpdateTransactionDraft(ctx context.Context, arg UpdateTransactionDraftParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionDraft,
		arg.ID,
		arg.OrganizationID,
		arg.Description,
		arg.Currency,
		arg.Category,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Status,
		&i.Description,
		&i.TotalAmount,
		&i.Currency,
		&i.Category,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByEmail,
		&i.CreatedByRole,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
